Json
PKUHPC/scow-deployment pull request #2
Opened 2022-09-28 05:36 UTC by huangjun0210

使用python来动态生成docker-compose文件，生成的文件格式为json

2022-09-28 07:22 UTC, ddadaal requested changes

2022-09-28 07:22 UTC, ddadaal commented on README.md
> +python main.py
python文件取一个有意义的名称，比如`generate.py`

2022-09-28 07:22 UTC, ddadaal commented on README.md
> +docker-compose -f docker-compose.json up -d
`-f`是必须的吗？如果目录下存在docker-compose.json，docker-compose是否可以自动识别，而不需要手动指定compose文件？

2022-09-28 07:22 UTC, ddadaal commented on config.py
> +BASE_PATH = ""
这个`以/开头，不要以/结尾，如果是根路径写空格`的限制非常不合直觉，这是因为之前使用环境变量的时候，只能直接死板地环境变量写什么，compose文件里的参数就设定什么，不能根据设定的值进一步处理。但是现在我们加了一步用python对用户的配置预处理，最后的compose文件里具体生成什么是**可以**预处理的。所以用户的配置里就不需要这种不合直觉的限制了。

这里的BASE_PATH以及下面的PORTAL/MIS_BASE_PATH都可以取消这一限制。只需要注明`以/开头，不要以/结尾`就可以了。在生成compose的文件的时候，根据用户的输入做判断，如果值是`/`，则生成的值是``，否则就是用户的值。

另外，为了保证用户不要写错配置，在生成的代码中增加对这些参数的检查，如果发现用户什么都没写、或者以/结尾了，就报错

2022-09-28 07:22 UTC, ddadaal commented on config.py
> +PORTAL_DEPLOYED = True
这些关于门户的配置（以及下面关于管理系统和fluentd的配置）可以组织成一个对象，如下：

如果用户不部署门户系统，则

```python
PORTAL = False
```

如果用户配置，则

```python
PORTAL = {
  "BASE_PATH": "/",
  "IMAGE_POSTFIX": "root",
}
```

这样也可以防止用户不把该写的配置写完。

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +        self.volumes = volumes
用一个class来组织Compose的配置非常好。

更进一步的，可以给这个类增加一些方法，例如`add_service`，后续添加服务的代码都通过这个方法往Compose对象中增加。这个方法可以处理一些公共逻辑，比如给服务增加`restart: unless-stopped`、增加fluentd配置等，进一步简化代码。

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +def configItemIsNotNul(configStr):
命名风格要统一：`config_item_is_not_null`

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +        return True
简化：`return not config_str.isspace()`

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +    log_driver['options'] = opt
这些都可以用dict字面量形式编写，更直观，下面的一样。即使有需要运算的部分，也可以把不需要运算的部分先用dict字面量形式编写，然后接下来再在这个字面量上继续修改。

```python
log_driver = {
  "driver": "fluentd",
  "opt": {
     "fluentd-address": "localhost:24224",
  }
}
```

另外引号风格统一，要么都用单引号要么都用双引号

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +    print("File generated successfully! ")
写清楚生成了什么文件：`docker-compose.json and db.sh`

2022-09-28 07:22 UTC, ddadaal commented on fluent.conf
> +<source>
fluentd相关的文件可以放到单独的`fluentd`目录下

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +    os.system('chmod +777 ' + log_dir)
python自带有文件操作的模块，不要使用os.system执行shell命令

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +    # config.PORTAL_BASE_PATH 未定义
按readme.md中说的把相关配置整合到一起的方式修改后，这里就不需要判断用户是不是没有设置某个配置了。如果用户没有配置，python自己会报错，不用自己处理

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +    environment = ["BASE_PATH=" + config.BASE_PATH, "PORTAL_PATH=" + portal_base_path, "MIS_PATH=" + mis_base_path]
设置服务的环境变量的时候，为了可读性，建议在这里把环境变量写成dict字面量的形式，然后编写一个单独的函数，把dict字面量转换为`KEY=VALUE`格式的数组

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +        gateway["depends_on"] = ["log"]
重复代码，抽象为一个函数

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +        os.system('chmod +777 db.sh')
使用python自带的文件操作模块更改文件权限

2022-09-28 07:22 UTC, ddadaal commented on main.py
> +        file = open('db.sh', 'w')
文件句柄没有关闭。使用with语句打开文件`with open('db.sh', 'w') as f`

2022-09-28 07:57 UTC, ddadaal commented
config.py改成config-example.py，然后把config.py gitignore掉。和原来的.env.example和config-example一样，防止我们对这些文件的更新与用户自己改的冲突

2022-09-29 01:45 UTC, huangjun0210 commented on README.md
> +python main.py
1

2022-09-29 01:49 UTC, huangjun0210 commented on README.md
> +docker-compose -f docker-compose.json up -d
docker-compose.yaml是默认文件，docker-compose.json需要-f

2022-09-29 02:42 UTC, ddadaal commented on README.md
> +docker-compose -f docker-compose.json up -d
好的

2022-10-08 03:16 UTC, huangjun0210 commented on config.py
> +PORTAL_DEPLOYED = True
1

2022-10-08 03:17 UTC, huangjun0210 commented on main.py
> +        self.volumes = volumes
1

2022-10-08 03:18 UTC, huangjun0210 commented on main.py
> +def configItemIsNotNul(configStr):
1

2022-10-08 03:18 UTC, huangjun0210 commented on main.py
> +        return True
1

2022-10-08 03:19 UTC, huangjun0210 commented on main.py
> +    log_driver['options'] = opt
1

2022-10-08 03:19 UTC, huangjun0210 commented on main.py
> +    print("File generated successfully! ")
1

2022-10-08 03:19 UTC, huangjun0210 commented on fluent.conf
> +<source>
1

2022-10-13 08:15 UTC, ddadaal requested changes

2022-10-13 08:15 UTC, ddadaal commented on README.md
> +```
这里加一句：每次修改了config.py都需要重新运行generate.py脚本以生成对应的docker-compose文件

2022-10-13 08:15 UTC, ddadaal commented on config-example.py
> +# MIS.IMAGE_POSTFIX: 管理系统镜像后缀
DB_PASSWORD注释一下：管理系统数据库的密码。第一次启动管理系统时会使用此密码初始化管理系统数据库，之后如需修改需要手动在数据库中修改

2022-10-13 08:15 UTC, ddadaal commented on generate.py
> +    try:
这里应该可以先判断目录是否存在，如果不存在再makedirs吧？不需要try catch

2022-10-13 10:48 UTC, ddadaal requested changes
`docker-compose -f docker-compose.json`太长了，用户每次都要输入这么多很麻烦。

可以加一个可执行的compose.sh文件，内容如下：

```
docker-compose -f docker-compose.json $@
```

这样，用户可以直接执行`compose.sh up/pull`等来执行docker compose命令。

记得加文档

2022-10-13 10:48 UTC, ddadaal commented on README.md
> +
这里开一个二级标题详细讲一下fluentd收集日志功能：

- 各个容器的日志具体保存在LOG_DIR的什么位置
- 说清楚开了收集日志就无法通过`docker-compose logs`获取日志

等等这些

2022-10-13 10:48 UTC, ddadaal commented on generate.py
> +import config as cfg
import了两次

2022-10-13 10:48 UTC, ddadaal commented on generate.py
> +            os.chmod("db.sh", stat.S_IRWXO)
这个db.sh的权限是------rwx，也就是当前用户和当前组都不能读，只有其他组可以读……
应该改成755

2022-10-13 10:52 UTC, ddadaal commented
为了用户的使用方面，之后还可以实现成这样：

- 每次用户执行compose.sh的时候，都执行一遍generate.py，保证用户不会忘记生成json文件
- generate.py不把输出输出到文件中，而是打回stdout，compose.sh直接把stdout给docker-compose，这样就不需要管生成的compose文件了
- 把db.sh和compose.sh合并，输入`compose.sh db`的时候，就自动进入数据库

这些之后都可以考虑

2022-10-13 10:55 UTC, ddadaal commented on .gitignore
> +/config.py
再忽略一个__pycache__目录。python执行的时候会生成这些文件

2022-10-13 10:58 UTC, ddadaal commented
compose.sh和db.sh要加一个判断：有的机器上是以手动安装的docker compose （https://docs.docker.com/compose/install/linux/#install-the-plugin-manually ），没有`docker-compose`命令，而只有`docker compose`命令。需要先判断一个机器上是不是有`docker-compose`，如果没有的话，使用`docker compose`命令。如果两个都没有，就报个错，给个docker compose的官方安装地址让用户去装

2022-10-13 11:11 UTC, ddadaal requested changes

2022-10-13 11:11 UTC, ddadaal commented on generate.py
> +        self.environment = environment
把volumes和enviroment从dict处理成正确的格式的函数（dict_to_array，tuple_to_array）可以在这里调用，而不是给Service的调用者来调用。这样，在创建Service对象的时候，创建者只需要传入一个dict就可以了，具体应该处理成什么格式不需要调用者来管。

2022-10-13 11:11 UTC, ddadaal commented on generate.py
> +def dict_to_array(d):
这个函数在把环境变量从dict处理成array的时候，处理错了。

传入的env
```python
{
  "env1": "envvalue1",
  "env2": "envvalue2"
}
```

现在处理成了：

```json
[
  "env1:envvalue1",
  "env2:envvalue2"
]
```

应该是

```json
[
  "env1=envvalue1",
  "env2=envvalue2"
]
```

文档：https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers

2022-10-13 11:11 UTC, ddadaal commented on generate.py
> +    log = Service("log", "fluentd:v1.14.0-1.0", tuple_to_array(log_ports), dict_to_array(log_volumes), None)
fluentd的版本建议提出来成为一个常量，这样之后好改

2022-10-13 11:32 UTC, ddadaal commented
生成几个BASE_PATH的逻辑不正确。正确的逻辑应该是文档这里说的：https://pkuhpc.github.io/SCOW/docs/common/customization/basepath#base_path%E5%A1%AB%E5%86%99%E8%A7%84%E5%88%99

COMMON.BASE_PATH和PORTAL/MIS.BASE_PATH的逻辑不一样。如果COMMON.BASE_PATH是`/`，那么生成的gateway的BASE_PATH是**空**；如果PORTAL/MIS.BASE_PATH是`/`，对应生成的几个环境变量是`/`。

2022-10-17 08:42 UTC, ddadaal requested changes

2022-10-17 08:42 UTC, ddadaal commented on generate.py
> +def dict_to_array(d, *p):
d、p分别是什么意思？参数名字取有意义的

2022-10-17 08:42 UTC, ddadaal commented on generate.py
> +def generate_path(p, s):
不要吝惜参数名长度，参数取名取有意义的

2022-10-17 08:42 UTC, ddadaal commented on generate.py
> +        os.chmod('compose.sh', stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
给一个脚本文件设置可执行权限是重复代码，提取成一个函数

2022-10-17 08:42 UTC, ddadaal commented on README.md
> +sh compose.sh up -d
`./compose.sh`也可以吧？是不是./简单一点

2022-10-17 08:42 UTC, ddadaal commented on README.md
> +# 卸载
停止服务 是不是直观一点

2022-10-17 08:42 UTC, ddadaal commented on README.md
> +sh compose.sh up -d
启动服务

2022-10-17 08:42 UTC, ddadaal commented on generate.py
> +            file.write("docker-compose -f docker-compose.json exec db mysql -uroot -p'" + db_passwd + "'")
docker-compose使用cmd_str变量

2022-10-17 08:42 UTC, ddadaal commented on README.md
> +|   FLUENTD.LOG_DIR    |                                 fluentd 收集日志的目录                                  |
这节可以删了吧，反正config.py里有

2022-10-17 08:42 UTC, ddadaal commented on README.md
> +## 生成 Docker compose 文件、compose.sh文件和 db.sh 文件
标题：编写并生成配置文件

2022-10-20 06:43 UTC, ddadaal requested changes

2022-10-20 06:43 UTC, ddadaal commented on generate.py
> +            compose_f.close()
这里是在读取compose.sh的文件然后替换`python generate.py`，为什么要这么做？如果之后compose.py文件改了，加了新语句，这里是不是又要改？

python有多行字符串语法，用多行字符串+格式字符串语法生成db.sh会清晰很多

```python
content = f"""
if docker compose &> /dev/null; then compose="docker compose";
elif docker-compose &> /dev/null; then compose="docker-compose";
else echo -e "Docker Compose ...."; exit 1; fi

$compose exec db mysql -uroot -p '{db_passwd}'
"""
```

2022-10-20 06:43 UTC, ddadaal commented on generate.py
> +        return False
现在不在python里判断docker-compose还是docker compose里，这个可以删了

2022-10-20 06:43 UTC, ddadaal commented on README.md
> +python generate.py
现在不需要手动生成文件了。但是需要交代每次运行compose.sh的时候会生成docker-compose.json和db.sh文件

2022-10-20 09:28 UTC, huangjun0210 commented on generate.py
> +            compose_f.close()
多行字符串因为在代码中有缩进，导致生成的db.sh文件格式不太好，改成如下形式：
content = "if docker compose &> /dev/null; then compose='docker compose';\n" \
                      "elif docker-compose &> /dev/null; then compose='docker-compose';\n" \
                      "else echo -e 'Docker Compose is not installed, refer to this connection for installation:\n" \
                      "https://docs.docker.com/compose/install/linux/#install-the-plugin-manually'; exit 1; fi\n" \
                      "$compose -f docker-compose.json  exec db mysql -uroot -p'" + db_passwd + "'"

2022-10-25 02:04 UTC, merged